spring:
  application:
    name: car-share-hub

  datasource:
    url: jdbc:postgresql://localhost:5432/carshare?options=-c%20timezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false

server:
  port: 8080

jwt:
  secret: my-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long
  expiration: 86400000
